# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # assumes the Dockerfile is in the root (.)
      - name: Build Docker image
        run: docker build -t stylesprint .

      # assumes a set of unit tests were defined
      - name: Run tests
        run: docker run stylesprint python -m unittest discover

  deploy:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Login to DockerHub
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{secrets.DOCKER_USERNAME }} --password-stdin
        - name: Push Docker image
          run:  docker tag stylesprint:latest ${{ secrets.DOCKER_USERNAME}}/stylesprint:latest
                docker push ${{ secrets.DOCKER_USERNAME}}/stylesprint:latest
